### ISSUE TITLE
Fails to deserialize unless there is trailing whitespace

### ISSUE THREAD

**Issue by dtolnay** [Canop/deser-hjson#1]
In https://github.com/serde-rs/serde-rs.github.io/pull/121#issuecomment-777270114 I was surprised that deser-hjson failed to deserialize i32 from the input `1` -- it took either trailing space or trailing newline for it to succeed.

```rust
fn main() {
    println!("{}", deser_hjson::from_str::<i32>("1").unwrap_err());
}
```

```console
Eof at 1:1 at "1"
```

Your PR described Hjson as a superset of JSON so I would have expected that to work, as `1` is valid JSON.

**Comment by Canop** [comment]
> Your PR described Hjson as a superset of JSON so I would have expected that to work, as 1 is valid JSON.

It **is** a bug

**Comment by Canop** [comment]
I've fixed the bug. I'll push soon with a related test suite checking other similar cases.
