### ISSUE TITLE
the attached hjson file can't be parsed

### ISSUE THREAD

**Issue by shi-yan** [Canop/deser-hjson#19]
the following example can't be parsed. but it's legit. 

you can verify it here https://hjson.github.io/try.html

```
{
  title : CodeStage example
  repo : https://github.com/shi-yan/codestage
  # need to have the slash
  prefix : ""
  target : dist
  url : "http://localhost:8000"
  meta_image : meta.png
  description : 
    '''CodeStage is a static site generator to build JS playground demos.'''
  utilities : [ "khronos",  "tdl" ]
}
```

the error message I got was 

```
Error: Eof at 11:3 at "utilities : [ \""
```

**Comment by Canop** [comment]
This would probably be solved with the work of @pamaury on multiline values in https://github.com/Canop/deser-hjson/pull/15

**Comment by Canop** [comment]
It should be OK now. 
There are some tests at https://github.com/Canop/deser-hjson/blob/main/tests/multiline_strings.rs
