### ISSUE TITLE
Braceless hjson not supported

### ISSUE THREAD

**Issue by bend-n** [Canop/deser-hjson#7]
```hjson
a: 4
```
is valid hjson.

This is not supported by this crate.
It errors with
```rs
Syntax { line: 1, col: 2, code: ExpectedMap, at: ": 4\n" }
```

**Comment by Canop** [comment]
Thanks, I hadn't noticed it was allowed again.

> Hjson allows you to omit {} for the root object so that a config file can contain nothing but keys and values, similar to YAML.
> Note: This feature was previously marked as deprecated but is now officially supported again. If you need maximum portability with your Hjson files, then we recommend you keep the root braces in case a third party implementation doesn't support it.

I'll have a look and try to support braceless Hjson.

**Comment by Canop** [comment]
It seems to work: https://github.com/Canop/deser-hjson/pull/8

Code isn't really pretty, but seems OK.

If you think about other cases than the ones [in the tests](https://github.com/Canop/deser-hjson/pull/8/files#diff-d4150d9c2b6bcf988bac2ad67c585a69677ad893ad8cb51fbd777749ac3fbf00), don't hesitate to make suggestions.

**Comment by Canop** [comment]
BTW I've tested it in Broot and I like that I can remove an indentation level, so I should publish a new version soon enough if we don't find problems.

**Comment by bend-n** [comment]
What is Broot?

**Comment by Canop** [comment]
This: https://dystroy.org/broot/
